### ISSUE TITLE
Latest update causes wrong colors

### ISSUE THREAD

**Issue by aos** [lifepillar/vim-gruvbox8#11]
After updating to the latest (the commit with migrating to Colortemplates v2), the colorscheme is way off. It's not even gruvbox anymore:

Some javascript:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/25783780/59959364-cd72f300-9483-11e9-8a17-d001aa7ff643.png">

A piece of my .vimrc:
<img width="466" alt="image" src="https://user-images.githubusercontent.com/25783780/59959370-dfed2c80-9483-11e9-98bc-3c6f05c5709d.png">

I'm using `nvim` v0.3.7 on iTerm2 3.2.9. What other info can I give you to make this easier to debug?

**Comment by lifepillar** [comment]
You must set `termguicolors` *before* loading the color scheme.

**Comment by aos** [comment]
That fixed it thanks ! Any reason for why this changed? Is it because you use `termguicolors` to determine colorscheme template?

Will close ticket. Just curious.

**Comment by lifepillar** [comment]
There are essentially two ways to define highlight groups in a color scheme:

- one-for-all, i.e., one definition for the terminals and GUI:

```vim
hi Foobar ctermfg=123 guifg=#abcdef
```

- separate definitions, one for terminal colors and one for GUI colors:

```vim
if has(‘termguicolors’)
  hi Foobar guifg=#abcdef
else
  hi Foobar cterm=123
endif
```

When you set `termguicolors`, Vim switches from using the `cterm` definitions to using the `gui` definitions (when you set `notermguicolors` it does the opposite). In the one-for-all approach, there’s no problem, because both have been defined. With the latter approach, the color scheme must be reloaded to update the definitions.

Colortemplate (the plugin I use to generate the color scheme) has moved from the one-for-all approach to the separate definitions approach. That’s why you need to set `termguicolors` then load the color scheme.

While the one-for-all approach might seem preferable because more forgiving, in fact the latter approach is cleaner, more efficient, and forces the user to use a logically correct configuration (first you choose whether to use GUI colors or not, then define the highlight groups), which is also a more robust configuration (it works with all color schemes, no matter how they are defined).

**Comment by aos** [comment]
Thank you for a thoughtful explanation!
