### ISSUE TITLE
This plugin does not work well for Markdown files when switch back and forth between different color schemes

### ISSUE THREAD

**Issue by jdhao** [lifepillar/vim-gruvbox8#25]
The behavior of this plugin is different from that of the original [gruvbox colorscheme](https://github.com/morhetz/gruvbox). When switching from other colorscheme to gruvbox8, highlight for header, inline link, inline code will lost, resulting a Markdown file barely readable. The original gruvbox colorscheme does not exhibit this behavior.

To reproduce, use the following minimal config:

```
set runtimepath+=/path/to/gruvbox8
set runtimepath+=/path/to/original/gruvbox
```

+ Open neovim with `nvim -u minimal.vim test.md`.
+ Switch to gruvbox colorsheme `:color gruvbox`. The highlight for header, inlink link etc. works.
+ Switch to gruvbox8 colorshceme `:color gruvbox8`. The highlight for header, inlink link etc. is lost. All text are now in plain color.

The content of test.md:

```markdown
# demo header

inline link: [some links](http://www.foobar.com)
inline code: `a=a+c`
```

**Comment by lifepillar** [comment]
Does that happen if you put this in your `vimrc`?

    let g:gruvbox_filetype_hi_groups = 1

**Comment by jdhao** [comment]
@lifepillar  `let g:gruvbox_filetype_hi_groups = 1` works.

**Comment by lifepillar** [comment]
FIY, the behaviour you observe is due to [a long-standing Vim issue](https://github.com/vim/vim/issues/4405), which has been fixed in Vim recently, but, apparently, not in Neovim.

The fix I have suggested works because, with that setting, the same filetype-specific highlight groups defined by the original Gruvbox are also loaded by Gruvbox8.
