### ISSUE TITLE
cant get operators highlight in go file

### ISSUE THREAD

**Issue by taigacute** [lifepillar/vim-gruvbox8#5]
hi i use `vim -go` and have this setting` let g:go_highlight_operators = 1` .  i cant get any operators highlight in go file when use gruvbox8. my gruvbox8 set
```
 [[plugins]]
 repo = 'lifepillar/vim-gruvbox8'
 hook_add = '''
  let g:gruvbox_filetype_hi_groups = 1
  let g:gruvbox_plugin_hi_groups = 1
'''
```
![term](https://user-images.githubusercontent.com/41671631/56420789-fd5e1880-62d1-11e9-9dd9-95f88dd31423.gif)

**Comment by lifepillar** [comment]
Setting `let g:go_highlight_operators = 1` has the effect of defining a `goOperator` highlight group that links to `Operator`. In Gruvbox 8 (and in the original Gruvbox, IIRC) `Operator` in turn links to `Normal`. That's why you don't see operators highlighted differently from normal text.

But I may change the definition of `Operator`. How do you propose to highlight operators?

**Comment by taigacute** [comment]
I refer to some colorscheme, most of the theme's `operator` highlight group the same as `func if` They are orange in gruvbox. how do you feel? Is too much orange glaring?

**Comment by lifepillar** [comment]
Mmh, maybe. How about `hi! link Operator Define`?

**Comment by taigacute** [comment]
maybe  `blue`?

**Comment by lifepillar** [comment]
`blue` is used for `Identifier`, so I chose `aqua` instead (slightly lighter). Please try the current master.

**Comment by taigacute** [comment]
hi @lifepillar  i tried it. it looks like this.
![123](https://user-images.githubusercontent.com/41671631/56467792-1263b480-6456-11e9-9c73-dd12f6608645.png)
seems good thanks for your work
