### ISSUE TITLE
Can you change some gruvbox8 colors for jsx?

### ISSUE THREAD

**Issue by taigacute** [lifepillar/vim-gruvbox8#7]
hi  @lifepillar , The color of the key parts is overlapping, although it is bold, it does not look good on the jsx file. What do you think?by the way  i use  [vim-jsx-improve](https://github.com/neoclide/vim-jsx-improve) plugin for `js/jsx`
![gruvbox8](https://user-images.githubusercontent.com/41671631/57580795-a7e7e680-74e0-11e9-9aa1-097af76e4d8c.png)

Here are some of the themes in jsx performance. 
papercolor
![papercolor](https://user-images.githubusercontent.com/41671631/57580803-cfd74a00-74e0-11e9-978c-15cf4f94119b.png)
solarized8
![solarized8](https://user-images.githubusercontent.com/41671631/57580806-d5349480-74e0-11e9-919c-a75d182f5092.png)
dracula
![dracula](https://user-images.githubusercontent.com/41671631/57580807-da91df00-74e0-11e9-8372-3c0f62b61ee9.png)

**Comment by lifepillar** [comment]
Sure. It would help if you could identify the involved highlight groups, because I don't use jsx. Looking at https://github.com/MaxMEllon/vim-jsx-pretty, it might be `jsxTag`, `jsxTagName`, `jsxAttrib`, etc…

Looking at your screenshots, though, it looks like Gruvbox is using the same color for two different base highlight groups—which is not good, in general… I'll need to take a look.

**Comment by taigacute** [comment]
ok i will check the highlight groups which jsx used

**Comment by lifepillar** [comment]
That's a good idea. I will compare with Solarized 8.

**Comment by taigacute** [comment]
@lifepillar   i found the structure is different between gurbox8 and solarized8.  didnt found the filetype setting in solarized8.

**Comment by taigacute** [comment]
hi this pic is gruvbox in vscode .
![vs](https://user-images.githubusercontent.com/41671631/57826575-630cca00-77d6-11e9-89e3-d1fb7e976142.png)

**Comment by taigacute** [comment]
hi  i hacked this theme , remake some colors like js . and add some plugins. if i create a pr ,it will change some color .what do you think?

**Comment by lifepillar** [comment]
Thanks, I’ll take a look ASAP.

**Comment by taigacute** [comment]
If you think its ok, I will submit a pr, and remove my gruvbox.

**Comment by lifepillar** [comment]
Ops, sorry, I was reading too fast… Yes, sure, a PR is welcome!

**Comment by taigacute** [comment]
its ok, The problem is that the colors of the js and jsx files are set according to my preferences, and I modified the vim-jsx-improve plugin to add a new jsx highlight group. The overall color may not be acceptable for some people. It is too fancy. . Is there a dispute about pr?
![1](https://user-images.githubusercontent.com/41671631/57932834-5a0f1c00-78ee-11e9-805a-56994a4d97b7.png)

**Comment by lifepillar** [comment]
It looks nice, feel free to submit a PR!

Some context, though: I don't care much about adding filetype-specific syntax highlighting and willingly accept users's requests in this sense, because (a) the original Gruvbox already had them (i.e., it was already “corrupted”—see below) and (b) they are disabled by default.

But there are reasons why this type of highlighting shouldn't belong to a colorscheme. Please refer to these threads if you are curious:

- https://github.com/lifepillar/vim-solarized8/issues/59
- https://github.com/vim/vim/issues/2325

and especially Tim Pope's comments here:

- https://github.com/altercation/solarized/issues/102

That said, please proceed with your PR, it won't be rejected. Maybe, some day we'll find a better way to fix the issue mentioned in those threads.

**Comment by taigacute** [comment]
@lifepillar  hi  i create this repo [gruvbox9](https://github.com/taigacute/gruvbox9),just for `vim-jsx-plugin`,Will there be infringement? Because it doesn't work for most plugins, vim-jsx-plugin I added a new jsx synatxgroup。ask for your opinion。

**Comment by lifepillar** [comment]
Feel free to fork and modify. Just give credit to Gruvbox’s author and mention the license.

**Comment by taigacute** [comment]
thanks very much

**Comment by lifepillar** [comment]
To avoid any misunderstanding: Gruvbox's author is https://github.com/morhetz, not me :) And Gruvbox (and my fork) are distributed under the [MIT license](https://en.wikipedia.org/wiki/MIT_License).

**Comment by IvanKarnaukhov** [comment]
I like Dracula's style!
